### ISSUE TITLE
Update version of core for kubectl

### ISSUE THREAD

**Issue by agup006** [calyptia/charts#25]
versoin right now is 0.3.9 we should use latest

Also we should add parameters for INSTANCE_NAME + TAGS within the command

**Comment by niedbalski** [comment]
Will look shortly and re-release, seems to be an issue with the release action.

**Comment by niedbalski** [comment]
➜ charts (increase-version) ✗ helm search repo calyptia/core --versions | head -n2
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
calyptia/core	0.3.4        	v0.4.1     	A helm chart to deploy Calyptia Inc. core on Ku...

The releaser CI action was messed up, fixed by adding a fetch-depth:0 to the checkout action 👍🏻
